### PR TITLE
lego-UI-UX-restructure changes

### PR DESCRIPTION
**Pull request by kaushalvivek**
1. Documentation added to split modal
image

### CODE REVIEW

**Comment by deepanshu17** [comment]
👏
Thanks,
Deepanshu Jain
M: +91-8106541899

**Comment by kaushalvivek** [comment]
Example of auto-generated markdown from form input:
image

**Comment by kaushalvivek** [comment]
Example of the current UI for snippet input
image

**Comment by kaushalvivek** [comment]
@Anubhav2701 , there are issues with inserting snippet when lazy loading is used. Will have to change somethings about how that is done. Will think more about the best way to do it and add it later, if that's okay.

**Comment by kaushalvivek** [comment]
UI with Tags for filtering

image

**Comment by kaushalvivek** [comment]
Multiple tags per codebrick allowed, with tag labels.
image

**Comment by kaushalvivek** [comment]
The tag feature would be commented out in the next commit for a 2-tier hierarchical section implementation.

**Comment by kaushalvivek** [comment]
2 tier hierarchy in codebricks 
demo

**Pull request merged**
